//
// Created by berke on 4/2/2026.
//

#ifndef CONWAY_CONFIG_H
#define CONWAY_CONFIG_H

#define CELL_SIZE 40

#define ROW 25
#define COL ROW

#define SCREEN_WIDTH ROW * CELL_SIZE
#define SCREEN_HEIGHT ROW * CELL_SIZE

#define UI_HEIGHT 2

#define TOTAL_HEIGHT (SCREEN_WIDTH + UI_HEIGHT * CELL_SIZE)

#define FONT_SIZE 24

#define TEXT_Y SCREEN_HEIGHT + UI_HEIGHT * CELL_SIZE / 2 - FONT_SIZE / 2

#define MAX_HISTORY_SIZE 32

#define STEP_TIME 450

#endif //CONWAY_CONFIG_H